PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns0: <http://rdfunit.aksw.org/ns/core#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
prefix sdmx-attribute: <http://purl.org/linked-data/sdmx/2009/attribute#>
prefix msv: <http://stream-ontology.com/metrics-severity/>
PREFIX : <http://stream-ontology.com/maturitymodel/>

construct {
  ?qm a dqv:QualityMeasurement;
    qb:dataSet <env://QMD_URI> ;
    :refMetric ?metric ;
    :refDate ?start ;
    :refResource <env://datasource_identifier> ;
    sdmx-attribute:unitMeasure <http://www.wurvoc.org/vocabularies/om-1.8/Unit_of_measure> ;
    :measurementValue ?m_value ;
    dqv:isMeasurementOf ?metric ;
  	dqv:computedOn <env://datasource_identifier> ;
    dqv:value ?m_value .
}
where {
  	?metric a dqv:Metric ;
      msv:hasRatingValueOf ?m_value .
  bind(UUID() as ?qm)

  ?testbed a <http://rdfunit.aksw.org/ns/core#TestExecution> ;
      prov:startedAtTime ?start .
}
